import Toast from '@/components/toast';
import '@/styles/globals.css';
import { ReactNode } from 'react';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

interface Props {
  children: ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="ko">
      <body>
        {children}
        <Toast />
      </body>
    </html>
  );
}
